version: "3"
services:
  api:
    restart: always
    build:
      context: ./message-api
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo-db
    environment:
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=MESSAGES-DB

  ui:
    build:
      context: ./message-viewer
      dockerfile: Dockerfile.dev
    volumes:
      - /user/app/node_modules
      - ./message-viewer/:/usr/app
    depends_on:
      - api

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "7777:80"
    depends_on:
      - ui
      - api

  mongo-db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
