## development Dockerfile

## base image
FROM node:alpine 

WORKDIR /usr/app 

## install dependencies 

### make package.json in separate step to avoid installing npm dependencies every time we change in the code only 
COPY package.json . 
RUN npm config set strict ssl false 
RUN npm install 

## copy source files
COPY . . 

## default command to run every time container started
CMD ["npm", "run", "start"]