# base image
FROM maven:3.6.1-jdk-8-slim as builder

WORKDIR /usr/app

COPY pom.xml .

RUN mvn dependency:resolve

COPY src ./src

RUN mvn package

#RUN rm -rf ./src

VOLUME /tmp

EXPOSE 5001

# default command to run every time container started
CMD ["java","-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev", "-jar","./target/message-api-1.0.0.jar"]